version: 2

models:
  # 1. La Dimension Listings
  - name: dim_listings
    description: "Table de dimension contenant les détails descriptifs des logements."
    columns:
      - name: listing_id
        description: "Clé primaire unique du logement."
        tests:
          - unique
          - not_null

  # 2. La Table de Faits Availability
  - name: fact_availability
    description: "Table journalière d'occupation et de prix."
    columns:
      - name: listing_id
        tests:
          - not_null
          - relationships: # Vérifie que cet ID existe bien dans la table dim_listings
              to: ref('dim_listings')
              field: listing_id

  # 3. La Table de Faits Listings (Stats)
  - name: fact_listings
    description: "Métriques agrégées par logement (notes, nombre de reviews)."
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('dim_listings')
              field: listing_id

  # 4. La Table de Faits Reviews
  - name: fct_reviews
    description: "Détail de chaque commentaire laissé."
    columns:
      - name: review_id
        tests:
          - unique
          - not_null
      - name: listing_id
        tests:
          - relationships:
              to: ref('dim_listings')
              field: listing_id