version: 2

models:
  - name: stg_airbnb_listings
    columns:
      - name: listing_id
        tests: [not_null]

  - name: stg_airbnb_calendar
    columns:
      - name: listing_id
        tests: [not_null]
      - name: calendar_date
        tests: [not_null]

  - name: stg_airbnb_neighbourhoods
    columns:
      - name: neighbourhood
        tests: [not_null]
        
  - name: stg_airbnb_reviews
    columns:
      - name: review_id
        tests: [not_null]
      - name: listing_id
        tests: [not_null]
      - name: review_date
        tests: [not_null]
